#!/usr/bin/env bash
# Manage logout with rofi
option=`echo -e "suspend\nlock screen\nlogout\nreboot\npoweroff\nKill user $USER" | rofi -width 600 -dmenu -p system`
case $option in
    suspend)
        sudo /usr/bin/systemctl suspend ;;
    'lock screen')
        # i3lock -c 000000 ;;
        # i3lock -i ~/.config/backgrounds/wallhaven-3ke3dd_1920x1080.png ;;
        i3lock -c 000000 -i ~/.config/backgrounds/thethinkingatheist.png ;;
    logout)
        i3-nagbar -t warning -m 'Are you sure you want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit' ;;
    reboot)
        /usr/bin/systemctl reboot ;;
    poweroff)
       /usr/bin/systemctl poweroff ;;
    'kill user $USER')
       loginctl kill-user $USER ;;
esac
