#!/usr/bin/env bash
###############################################################################
# Script Name  : changevolume
# Description  : Changes volume with i3wm sxhkdrc keybindings
# Dependencies : pamixer
# Arguments    : up, down, mute (provided by keybinding)
# Author       : Copyright © 2025, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 22 Aug 2025
# Last updated : 22 Aug 2025
# Comments     : Original script by Drew Grif @ https://github.com/drewgrif
# TODO (Rick)  :
# License      : GNU General Public License, version 2
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

case "$1" in
	up)
		# Set the volume on (if it was muted)
		pamixer -u
		pamixer -i 2 --allow-boost
		send_notification "$1"
		;;
	down)
		pamixer -u
		pamixer -d 2 --allow-boost
		send_notification "$1"
		;;
	mute)
		pamixer -t
		if [[ "$(pamixer --get-mute)" == "true" ]]; then
			dunstify -i volume-mute -a "changevolume" -t 2000 -r 9993 -u low "Muted"
		else
			send_notification up
		fi
esac
