#!/usr/bin/env bash
###############################################################################
# Script Name  : logout
# Description  : manage i3 logout script using rofi
# Dependencies : rofi, i3lock
# Arguments    :
# Author       : Copyright © 2025, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 18 Nov 2021
# Last updated : 14 Jun 2025
# Version      : 2.0.25165
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

option=$(echo -e "suspend\nlock screen\nlogout\nreboot\npoweroff\nKill user $USER" | rofi -width 600 -dmenu -p system)
case $option in
    suspend)
        sudo /usr/bin/systemctl suspend ;;
    'lock screen')
        # i3lock -c 000000 ;;
        i3lock -c 000000 -i ~/.config/backgrounds/tux-1920x1080.png ;;
    logout)
        i3-nagbar -t warning -m 'Are you sure you want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit' ;;
    reboot)
        /usr/bin/systemctl reboot ;;
    poweroff)
        /usr/bin/systemctl poweroff ;;
    "kill user $USER")
        loginctl kill-user "$USER" ;;
esac
